[package]
name = "sol"
version = "0.1.0"
authors = ["william <williamborgeaud@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.3.1"
num-integer = "0.1.41"